title: My Portfolio
description: This is my personal portfolio site.
baseurl: "/Portfolio" # The subpath of your site, e.g., /Iportfolio
url: "https://Ammarach.github.io" # Your GitHub Pages URL
theme: jekyll-theme-minimal # The Jekyll theme you are using
github_username: Ammarach
